### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by sinakuhestani**
I changes some lines because 
1. Wildcard Roles * MUST NOT override dynamic roles [issue #11]
2. Dynamic Roles did not act as expected.

### CODE REVIEW

**Comment by lolix-kernel** [comment]
Hi, I new at the programming, and I don't understand why your code has problems with the tests. Can anyone explain me the reason, please?

Thanks in advance.

**Comment by alexdodonov** [comment]
@lolix-kernel right now I am trying to find out why do you have this issue.

**Comment by alexdodonov** [comment]
@lolix-kernel 

> Hi, I new at the programming, and I don't understand why your code has problems with the tests. Can anyone explain me the reason, please?

Looks like @sinakuhestani have changed callRoute($route) method, but have forgotten to update getCallback($route) method.

I have done it myself. Please try version 1.3.0

**Comment by lolix-kernel** [comment]
> @lolix-kernel
> 
> > Hi, I new at the programming, and I don't understand why your code has problems with the tests. Can anyone explain me the reason, please?
> 
> Looks like @sinakuhestani have changed callRoute($route) method, but have forgotten to update getCallback($route) method.
> 
> I have done it myself. Please try version 1.3.0

Thank you for replying.

**Comment by alexdodonov** [comment]
There is no need in these changes.

**Pull request closed without merging**
